# Generated by Django 5.0.3 on 2024-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
